# Generated by Django 6.0.1 on 2026-01-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_customuser_date_of_birth_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
