# Generated by Django 6.0.1 on 2026-01-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view', 'Can view profile'), ('can_create', 'Can create profile'), ('can_edit', 'Can edit profile'), ('can_delete', 'Can delete profile')]},
        ),
    ]
